version: 0.2
phases:
  install:
    commands:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - cd ./src
      - npm install
  build:
    commands:
      - echo Testing the code
      -  npm test
      - echo Removing dev dependencies
      - rm -Rf node_modules
      - npm install --production
  post_build:
    commands:
      - cd ../ && ls -R
      - cp stacks/api.stack.yml api.stack.yml
      - aws cloudformation package --template-file api.stack.yml --s3-bucket ${Bucket} --output-template-file stack.output.yml
artifacts:
  type: zip
  files:
    - stack.output.yml